version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '16686:16686' 
      - '14250:14250'  
      - '14268:14268'  
      - '9411:9411'    
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      traefik_network:

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ['--config=/etc/otel-collector-config.yml']
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml 
    ports:
      - '4317:4317' 
      - '4318:4318'
      - '55680:55680'
    depends_on:
      - jaeger
    networks:
      - traefik_network

networks: 
  traefik_network:  
    name: inlaze 
    driver: bridge