receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  debug: {}
  otlphttp:
    endpoint: 'http://jaeger:14268'

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlphttp]