entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik_network  

api:
  dashboard: true  
  insecure: false  

log:
  level: DEBUG  

# tracing:
#   serviceName: traefik
#   jaeger:
#     samplingServerURL: http://jaeger:5778/sampling
#     localAgentHostPort: jaeger:6831
#     propagation: jaeger

accessLog: {}

tracing:
  serviceName: traefik
  otlp:
    http:
      endpoint: http://jaeger-otel-collector-1:4317/v1/traces

tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/certs/web.crt"  
        keyFile: "/certs/web.key"  

certificatesResolvers:
  default:
    acme:
      email: devops@inlaze.com  
      storage: "/acme.json"  
      tlsChallenge: {}

