entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik_network  
    
  http:
    endpoint: "http://172.168.30.215:8089/containers"
    pollInterval: "60s"

api:
  dashboard: true  
  insecure: true  

log:
  level: DEBUG  


accessLog: {}

# tracing:
#   serviceName: traefik
#   otlp:
#     http:
#       endpoint: http://otel-collector:4318/v1/traces

# tls:
#   stores:
#     default:
#       defaultCertificate:
#         certFile: "/certs/web.crt"  
#         keyFile: "/certs/web.key"  

# certificatesResolvers:
#   default:
#     acme:
#       email: devops@inlaze.com  
#       storage: "/acme.json"  
#       tlsChallenge: {}


# certificatesResolvers:
#   myresolver:
#     acme:
#       email: aux.it@inlaze.com
#       storage: /acme.json
#       tlsChallenge: {}