entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik_network  

api:
  dashboard: true  
  insecure: false  

log:
  level: DEBUG  

# tracing:
#   serviceName: traefik
#   jaeger:
#     samplingServerURL: http://jaeger:5778/sampling
#     localAgentHostPort: jaeger:6831
#     propagation: jaeger

accessLog: {}

# tracing:
#   serviceName: traefik
#   jaeger:
#     samplingServerURL: http://172.168.30.116:5778/sampling
#     localAgentHostPort: 172.168.30.116:6831
#     propagation: 172.168.30.116

tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/certs/web.crt"  
        keyFile: "/certs/web.key"  

certificatesResolvers:
  default:
    acme:
      email: devops@inlaze.com  
      storage: "/acme.json"  
      tlsChallenge: {}

