entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik_network  

api:
  dashboard: true  
  insecure: false  

log:
  level: DEBUG  


accessLog: {}

tracing:
  serviceName: traefik
  otlp:
    http:
      endpoint: http://otel-collector:4318/v1/traces

tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/certs/web.crt"  
        keyFile: "/certs/web.key"  

certificatesResolvers:
  default:
    acme:
      email: devops@inlaze.com  
      storage: "/acme.json"  
      tlsChallenge: {}

