entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  # file:
  #   filename: "/dynamic.yml"
  #   watch: true
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik_network  
    
  http:
    endpoint: "http://192.168.1.10:8089/containers"
    pollInterval: "10s"

api:
  dashboard: true
  insecure: true

log:
  level: DEBUG

accessLog: {}
