version: '3.8'

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000                
      - PGID=1000                 
      - TZ=America/Bogota         
      - SERVERURL=vpn.inlazetest.com
      - SERVERPORT=51820          
      - PEERS=3                   
      - PEERDNS=auto        
      - INTERNAL_SUBNET=10.13.13.0 
    volumes:
      - ./wireguard-config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp           
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  wg-easy:
    image: weejewel/wg-easy
    container_name: wg-easy
    environment:
      - WG_HOST=vpn.inlazetest.com  
      - PASSWORD=$port2024**      
      - WG_PORT=51820           
    ports:
      - 51821:51821             
    volumes:
      - ./wireguard-config:/etc/wireguard 
    depends_on:
      - wireguard
    restart: unless-stopped

