version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer-vm.inlazetest.com`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.entrypoints=web"
    container_name: portainer
    ports:
      - "9443:9443"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - traefik_network

volumes:
  portainer_data:

networks: 
  traefik_network:  
    name: inlaze 
    driver: bridge
    external: true
